apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trace-ai-server
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: europe-west1-docker.pkg.dev/PROJECT_ID/cloud-run-source-deploy/trace-ai-server:TAG
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: '4'
              memory: '8Gi'
            requests:
              cpu: '2'
              memory: '4Gi'
          env:
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'production'
